// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CheckoutSessionResponse struct {
	SessionID string `json:"sessionId"`
}

type Mutation struct {
}

type NewProject struct {
	ProjectName string `json:"projectName"`
}

type PortalSessionResponse struct {
	SessionURL string `json:"sessionUrl"`
}

type Query struct {
}

type SubscriptionData struct {
	CurrentPeriodStart string `json:"currentPeriodStart"`
	CurrentPeriodEnd   string `json:"currentPeriodEnd"`
	Status             string `json:"status"`
	Interval           string `json:"interval"`
	PlanName           string `json:"planName"`
	CostInUsd          int64  `json:"costInUsd"`
	LastFourCardDigits string `json:"lastFourCardDigits"`
	ResourcesIncluded  int    `json:"resourcesIncluded"`
	ResourcesUsed      int    `json:"resourcesUsed"`
}

type Userinfo struct {
	UserID   int64  `json:"userId"`
	Email    string `json:"email"`
	FullName string `json:"fullName"`
}
